---
# This playbooks configured existing openshift cluster to use glusterfs as backed storage for the registry
# Pre-reqs:
# Glusterfs/CRS/CNS cluster already deployed 
# Registry already deployed

- name: Configure invetory groups
  hosts: all:!controller:!bastion
  tasks:
    - set_fact:
        openshift_hosted_registry_storage_kind: glusterfs
        openshift_storage_glusterfs_heketi_is_native: "{{ postdeploy_openshift_storage_glusterfs_heketi_is_native }}"
        openshift_storage_glusterfs_heketi_topology_load: "{{ postdeploy_glusterfs_heketi_topology_load }}"
        openshift_storage_glusterfs_storageclass: "{{ postdeploy_openshift_storage_glusterfs_storageclass }}"
        openshift_storage_glusterfs_block_storageclass: "{{ postdeploy_glusterfs_block_storageclass }}"
    - name: Add glusterfs nodes to glusterfs group for playbooks
      add_host:
        name: "{{ item }}"
        groups: glusterfs
      with_items:
      - "{{ groups['postdeploy_glusterfs'] }}"

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/config.yml
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/config.yml
                                                                                             
