---
# tasks file for docker

- name: Check for Atomic Host
  stat: path=/run/ostree-booted
  register: atomic_host

- name: install docker
  yum:
    name: docker-{{ docker_version }}
    state: latest
  when: atomic_host.stat.exists == False

- name: check status of disk
  stat:
    path: "{{docker_storage_disk}}1"
  register: disk_check_result
  ignore_errors: True

- name: create phyical volume from device
  parted:
    device: "{{ docker_storage_disk }}"
    number: 1
    state:  present
    flags: [ lvm ]
    part_end: 100%
  when: disk_check_result.stat.exists == False

- name: create VG
  lvg:
   vg: "{{docker_vg_name}}"
   pvs: "{{docker_storage_disk}}1"
  register: createdockervg

- name: create LVOL /opt/docker/data
  lvol:
    vg: "{{docker_vg_name}}"
    lv: "{{docker_lv1_name}}"
    size: "{{docker_lv1_size}}"
  when: 
    - createdockervg.changed
    - docker_data|bool == true

- name: create fs
  filesystem:
    fstype: xfs
    dev: /dev/mapper/{{docker_vg_name}}-{{docker_lv1_name}}
  when: 
    - createdockervg.changed
    - docker_data|bool == true

- name: create LVOL /var/lib/docker
  lvol:
   vg: "{{docker_vg_name}}"
   lv: "{{docker_lv2_name}}"
   size: "{{docker_lv2_size}}"
  when:
   - createdockervg.changed
   - docker_var|bool == true
  
- name: create fs
  filesystem:
   fstype: xfs
   dev: /dev/mapper/{{docker_vg_name}}-{{docker_lv2_name}}
  when: 
   - createdockervg.changed
   - docker_var|bool == true

- name: Stop Docker service
  service:
   state: stopped
   name: docker 
  when: 
   - createdockervg.changed

- name: Mount /opt/docker/data
  mount:
    name: /opt/docker/data
    src: /dev/mapper/{{docker_vg_name}}-{{docker_lv1_name}}
    fstype: xfs
    state:  mounted
  when: docker_data|bool == true


- name: Mount /var/lib/docker
  mount:
   name: /var/lib/docker
   src: /dev/mapper/{{docker_vg_name}}-{{docker_lv2_name}}
   fstype: xfs
   state: mounted
  when: 
   - createdockervg.changed
   - docker_var|bool == true

- name: Change docker-storage configuration
  template:
   src: "{{ role_path }}/files/docker-storage-setup.j2"
   dest: /etc/sysconfig/docker-storage-setup
   owner: root
   group: root
   mode: 0644
  when: createdockervg.changed 

- name: Automatically configure Docker storage
  command: /usr/bin/docker-storage-setup
  when: createdockervg.changed

- name: Remove any usr data to clean disk
  command: rm -rf /opt/docker/data/*
  when: 
    - createdockervg.changed
    - docker_data|bool == true

- name: Remove any Docker configuration to clean disk
  command: rm -rf /var/lib/docker/*
  when: 
   - createdockervg.changed
   - docker_var|bool == true

- block:
  - name: Set HTTP proxy
    lineinfile:
      line: "HTTP_PROXY={{ openshift_http_proxy }}"
      path: /etc/sysconfig/docker
      regexp: '^HTTP_PROXY='
    when: openshift_http_proxy is defined
  
  - name: Set HTTPS proxy
    lineinfile:
      line: "HTTPS_PROXY={{ openshift_https_proxy }}"
      path: /etc/sysconfig/docker
      regexp: '^HTTPS_PROXY='
    when: openshift_http_proxy is defined
  
  - name: Set noproxy
    lineinfile:
      line: "NO_PROXY={{ openshift_no_proxy }}"
      path: /etc/sysconfig/docker
      regexp: '^NO_PROXY='
    when: openshift_no_proxy is defined

  - name: Configure additional registries
    template:
      src: registries.conf.j2
      dest: /etc/containers/registries.conf
  tags:
    - docker_config

- name: Start and enable Docker service
  service:
    name: docker  
    state: started
    enabled: yes
