---
# TODO: make idempotent by using oc_obj instead of command oc
- name: Preparing the secret file
  template:
    src: "bigip_secret.yml"
    dest: "/tmp/bigip_secret.yml"
  delegate_to: localhost

-ï»¿command: "oc delete secret bigip-login -n default --token {{ ocp_token }}"
  ignore_errors: yes

- name: Creating Big IP secret
  command: "oc create -f /tmp/bigip_secret.yml --token {{ ocp_token }}"

- name: Removing the secret file
  file:
    path: "/tmp/bigip_secret.yml"
    state: absent

- command: "oc delete serviceaccount bigip-ctlr -n default --token {{ ocp_token }}"
  ignore_errors: yes

- name: Creating a service account for bigip controller
  command: "oc create serviceaccount bigip-ctlr -n default --token {{ ocp_token }}"

- command: "oc delete clusterrole system:bigip-ctlr -n default --token {{ ocp_token }}"
  ignore_errors: yes

- name: Creating the bigip-ctrl Cluster Role
  command: "oc create -f cluster_role.yml -n default --token {{ ocp_token }}"
  args:
    chdir: "{{ role_path }}/files"

- name: Binding the bigip-ctrl Cluster Role with the service account
  command: "oc create -f cluster_role_binding.yml -n default --token {{ ocp_token }}"
  args:
    chdir: "{{ role_path }}/files"

- name: Preparing the deployment file
  template:
    src: "deployment.yml"
    dest: "/tmp/deployment.yml"
  delegate_to: localhost

- name: Creating the bigip-ctrl Deployment
  command: "oc create -f /tmp/deployment.yml -n default --token {{ ocp_token }}"

- name: Removing the deployment file
  file:
    path: "/tmp/deployment.yml"
    state: absent
...