---
# defaults file for ocp_configure_node
ansible_become: true

node_type: compute

# Minimum docker storage in GB
min_storage:
  master: 50
  infra: 50
  compute: 50
  registry: 50
  glusterfs: 50

# Memory values in GB
min_memory:
  master: 16
  infra: 16
  compute: 32
  registry: 16
  glusterfs: 16

min_cpus:
  master: 4
  infra: 2
  compute: 8
  registry: 2
  glusterfs: 2
  
docker_device: vdb
